version: '3.9'

services:
  app:
    build: .
    container_name: ObjectDetection
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - UV_COMPILE_BYTECODE=1
      - UV_LINK_MODE=copy
      - PYTHONPATH=/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "4"]

    restart: unless-stopped
